### ISSUE TITLE
Only show the create, edit buttons and forms if the user is a Content Editor

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/hca-atlas-tracker#138]
#### Need
Currently, the create and edit buttons and forms for atlas and source datasets show if the user is logged in but not registered. Instead, we need to show these forms only if the user has the role CONTENT_ADMIN.

#### Approach
1. Call the new[ /me](https://github.com/clevercanary/hca-atlas-tracker/issues/144) endpoint to determine the user's role after login.
2. Only show the create/update atlas and source dataset buttons if the user is a CONTENT_ADMIN.

**Comment by frano-m** [comment]
## User has view access only

#### View Atlases

![Image](https://github.com/clevercanary/hca-atlas-tracker/assets/18710366/365b6b2f-ac32-4cc2-aa71-5d60b614af79)

#### View / Edit Atlas (view only)

![Image](https://github.com/clevercanary/hca-atlas-tracker/assets/18710366/474d25bc-1f85-4b3c-81a1-9a2c7737eef1)

#### View Source Datasets

![Image](https://github.com/clevercanary/hca-atlas-tracker/assets/18710366/1c394782-4567-4af4-aef0-6a482495ba34)

#### View / Edit Source Dataset (view only)

![Image](https://github.com/clevercanary/hca-atlas-tracker/assets/18710366/04882872-e802-493c-9995-29b86e2723ba)

#### Create Atlas (user can only access this page via address bar)

![Image](https://github.com/clevercanary/hca-atlas-tracker/assets/18710366/32957070-791a-4507-80a3-953ca5217c06)
