### ISSUE TITLE
Show registration screen only for "UNREGISTERED" users.

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/hca-atlas-tracker#165]
On the front end if the /me endpoint returns a role of "UNREGISTERED" log the user out and forward to a /registration-required page where we can put some instructions.

### Registration Required 

Please email someone to request access to the HCA Atlas Tracker Beta.

**Comment by frano-m** [comment]
Ellen Todres [etodres@humancellatlas.org](mailto:etodres@humancellatlas.org)
