### ISSUE TITLE
Add target completion to the atlas view and edit forms

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/hca-atlas-tracker#231]
The dropdown is similar to the one for tasks as part of the edit page for atlases. 
Let's discuss.

**Comment by frano-m** [comment]
Add the dropdown as the last item to the General Information section.

https://www.figma.com/design/g60pHZLz78wfl0PvbksMb5/HCA-Tracker?node-id=47-1350&t=cTXZSjmIq4dxyHSU-4
