### ISSUE TITLE
Add count of component atlases to component atlas tab similar to source study count

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/hca-atlas-tracker#288]
![Image](https://github.com/clevercanary/hca-atlas-tracker/assets/3239697/24aaa1ed-cd5d-43fb-9ced-1a5fd72ee6e1)

**Comment by frano-m** [comment]
See https://github.com/clevercanary/hca-atlas-tracker/issues/287

**Comment by NoopDog** [comment]
This is unblocked @frano-m
