### ISSUE TITLE
Look into resolving more near-matches in title validation

### ISSUE THREAD

**Issue by hunterckx** [clevercanary/hca-atlas-tracker#323]
Look through existing tasks for cases that should match: https://tracker.data.humancellatlas.org/tasks?filter=%5B%7B%22categoryKey%22%3A%22description%22%2C%22value%22%3A%5B%22Update+project+title+to+match+publication+title.%22%5D%7D%5D

**Comment by hunterckx** [comment]
Pairs of titles that we may want to consider to be the same:

`Single-cell transcriptomics reveals cell-type-specific diversification in human heart failure`

`Single Cell Transcriptomics Reveals Cell Type Specific Diversification in Human Heart Failure`

Fails because punctuation is removed entirely for comparison, so here for example "singlecell" is compared to "single cell"

`Pathogen-induced tissue-resident memory T H 17 (T RM 17) cells amplify autoimmune kidney disease`

`Pathogen-induced tissue-resident memory TH17 (TRM17) cells amplify autoimmune kidney disease`

Probably can't be resolved without ignoring whitespace entirely ("T H 17" vs "TH17")

`Single-cell RNA sequencing identifies celltype-specific cis-eQTLs and co-expression QTLs`

`Single-cell RNA sequencing identifies cell type-specific cis-eQTLs and co-expression QTLs`

Also just a whitespace thing ("celltype" vs "cell-type")

`Local and systemic responses to SARS-CoV-2 infection in children and adults`

`The local and systemic response to SARS-CoV-2 infection in children and adults`

Very similar but one has an extra word so not sure if we'd even actually want to consider them the same

`Single-cell RNA-seq reveals ectopic and aberrant lung-resident cell populations in idiopathic pulmonary fibrosis`

`Single Cell RNA-seq reveals ectopic and aberrant lung resident cell populations in Idiopathic Pulmonary Fibrosis`

Again, the issue with hyphens being ignored entirely

`Single-cell RNA sequencing reveals profibrotic roles of distinct epithelial and mesenchymal lineages in pulmonary fibrosis`

`Single-cell RNA-sequencing reveals profibrotic roles of distinct epithelial and mesenchymal lineages in pulmonary fibrosis`

Also hyphens

`The single-cell transcriptomic landscape of early human diabetic nephropathy`

`The Single Cell Transcriptomic Landscape of Early Human Diabetic Nephropathy`

Hyphens

`Spatial proteogenomics reveals distinct and evolutionarily conserved hepatic macrophage niches`

`Spatial proteogenomics reveals distinct and evolutionarily-conserved hepatic macrophage niches`

Hyphens

`A single-cell atlas of human teeth`

`A single cell atlas of human teeth`

Hyphens

**Comment by hunterckx** [comment]
Other than the questionable extra-word one the only two types of problems here are differences in use of spaces and hyphen vs space; both of these could be resolved by completely ignoring whitespace in the comparison, though of course that could theoretically lead to different sequences of words being considered the same

If we just wanted to solve the hyphen one..... well it would be possible of course to allow punctuation to match both spaces and absences of characters but I'm not sure what the simplest way would be

**Comment by NoopDog** [comment]
We will leave the current match as is. Closing!
