### ISSUE TITLE
Example SQL for creating users with role related resources

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/hca-atlas-tracker#355]
@Hunter can you provide an example of how to create a user with and without the new roleRelatedResource field?
How do I create a STAKEHOLDER?
How do I create a INTEGRATION_LEAD and assign the lead a one or more atlases?

**Comment by hunterckx** [comment]
Create a stakeholder:
`INSERT INTO hat.users (disabled, email, full_name, role, role_associated_resource_ids) VALUES ('f', 'foo@example.com', 'Foo', 'STAKEHOLDER', '{}');`

Create an integration lead of two atlases:
`INSERT INTO hat.users (disabled, email, full_name, role, role_associated_resource_ids) VALUES ('f', 'bar@example.com', 'Bar', 'INTEGRATION_LEAD', '{01234567-89ab-cdef-0123-456789abcdef, fedcba98-7654-3210-fedc-ba9876543210}');`

**Comment by NoopDog** [comment]
Ok thx!
