### ISSUE TITLE
Why are some updated dates later than the completed dates what is changing?

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/hca-atlas-tracker#437]
Looking at the updated_at  in the reports section, some items  have an updated date later than the completion date e.g. 

<img width="1645" alt="image" src="https://github.com/user-attachments/assets/8b044f76-c1bd-4291-9848-710bfdae2b18">

What are the ways this can happen?

**Comment by hunterckx** [comment]
`resolved_at` is set to the current date only when the validation status changes to `PASSED` from something else, while `updated_at` is set to the current date any time the database entry is updated. I may be overlooking some other possibility, but I think the reason a validation would update without the status changing would be for something to change on the associated entities. (For example, a validation stores the list of atlases that the associated source study is in, so if the source study is added to an atlas that would cause the validation to update.)

**Comment by NoopDog** [comment]
Complete thx!
