### ISSUE TITLE
 [HCA Atlas Tracker] Add / remove Integration leads

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/hca-atlas-tracker#456]
#### Need
See [#195](https://github.com/clevercanary/cc-design/issues/195).

![Image](https://github.com/user-attachments/assets/3f3aa646-87f3-462c-8f52-3b0fa9789ef2)

#### Approach
* Add functionality to support add/remove of integration leads. 
  * Always show a blank lead row if no leads are specified.
  * Remove the current blank "second lead" functionality. That is, only show non-first lead rows that filled.
  * If a user clicks the "Add lead" button and then clicks "Save" without specify lead details, validate and show an error message.
  * The user must remove a empty lead before a save is allowed.
* Add corresponding UI (possibly assign to @frano-m if polishing is required to match mocks).

**Comment by NoopDog** [comment]
Complete! Thx @hunterckx
