### ISSUE TITLE
Handle "preprint" subtype in CrossRef API response

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/hca-atlas-tracker#86]
### Need
Crossref has a "subtype" in their publication metadata:

![Image](https://github.com/clevercanary/hca-atlas-tracker/assets/3239697/c5f2f62b-d6d0-4267-8198-b0e69280c2db)

The main subtypes we are interested in are "preprint" and "journal". We will need to see if the DOIs we see have different subtypes, but for now, this is the set of subtypes I can see is getting. 

When the "preprint" subtype is selected, there is no "journal" specified so we can't build our publication string.  We need to detect preprints and update the formation of the publication string to handle the preprint case.

### Approach

Pass through the subtype form crossref through to the UI so we can use it to help format the publication string and the source dataset display.

#### DOD

- [ ] 1. Add the publication subtype to the source database database entry.
- [ ] 2. Add the publication subtype to the source dataset API response
- [ ] 3. If the publication subtype is something other than "journal" or "preprint," reject the form and submit with an error "Unsupported publication subtype: ${subtype} on the DOI field. 
- [ ] 4. If the publication subtype is a preprint, and there's no `journal` value from `container-title`, `short-container-title`, or `institution`, set `journal` to `Preprint`. show the publication string like `Choudhury (2020) Preprint` on the list and create and update forms otherwise, use the preprint publication as normal like `Choudhury (2020) Bioarxiv`.
- [ ] 5. Tests for unsupported, journal and preprint subtypes API responses and publication string builder.

**Comment by frano-m** [comment]
LGTM @hunterckx thank you! 🚀

**Comment by NoopDog** [comment]
Complete
